---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```

```{r}
library(LaF)
# This function and code grab a random sample of rows from a large csv
#https://statcompute.wordpress.com/2018/04/28/read-random-rows-from-a-huge-csv-file/
sample1 <- function(file, n) {
  lf <- laf_open(detect_dm_csv(file, sep = "|", header = TRUE, stringsAsFactors= FALSE, factor_fraction = -1, fill = TRUE))
  return(read_lines(lf, sample(1:nrow(lf), n)))
}
 
circ <- sample1("~/Documents/GitHub/LIS-598-Sp2020-DC2-testing/Data/Casey Gabehart - Circulation by Title 6mo SIL 20200216.csv", 98)
```


```{r}
# This code reads in the entire dataset - very large!

# circ <- read_delim("~/Documents/GitHub/LIS-598-Sp2020-DC2-testing/Data/Casey Gabehart - Circulation by Title 6mo SIL 20200216.csv",
#                            delim = "|", 
#                            escape_double = FALSE, 
#                            trim_ws = TRUE)
```

```{r}
write_csv(circ, "~/Documents/GitHub/LIS-598-Sp2020-DC2-testing/Data/SnoIsleCircSample.csv", col_names = T)
```

